{% set name = "jsonschema2md" %}
{% set version = "0.9.0" %}
{% set sha256 = "03611e87afdf43d5f2479d7cbd89f21589aa2c823b2e6c86ea2c1dc7cb25bbed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}2/{{ name }}2-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - jsonschema2md = jsonschema2md:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.9
    - poetry >=0.12
  run:
    - python >=3.9, <4.0
    - PyYAML >=6.0.1, <6.1

test:
  imports:
    - jsonschema2md
  commands:
    - pip check
    - jsonschema2md --help
  requires:
    - pip

about:
  home: https://github.com/sbrunner/jsonschema2md
  summary: Convert JSON Schema to human-readable Markdown documentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ollyhensby
    - brynpickering
